In [2]:
from langchain_community.document_loaders import TextLoader # type: ignore

In [3]:
loader = TextLoader("news.txt")
data = loader.load()

In [4]:
data[0]

Document(page_content='Republicans join Donald Trump\'s attacks on justice system, campaign of vengeance for guilty verdict\nTrump still faces three other felony indictments\n\nByLISA MASCARO and MARY CLARE JALONICK AP logo\nSaturday, June 1, 2024 10:59PM\n\n\n\n\n\n\nRepublicans join Trump\'s attacks on justice system after verdict\n\nRepublicans lawmakers are joining former President Donald Trump\'s attacks on the justice system and a campaign of vengeance after his guilty verdict.\n\nRepublicans lawmakers are joining former President Donald Trump\'s attacks on the justice system and a campaign of vengeance after his guilty verdict.\nWASHINGTON -- Embracing Donald Trump\'s strategy of blaming the U.S. justice system after his historic guilty verdict, Republicans in Congress are fervently enlisting themselves in his campaign of vengeance and political retribution as the GOP runs to reclaim the White House.\n\nAlmost no Republican official has stood up to suggest Trump should not be th

In [5]:
from langchain.document_loaders.csv_loader import CSVLoader # type: ignore

loader = CSVLoader("addresses.csv")
data = loader.load()
len(data)


6

In [6]:
!pip install unstructured libmagic python-magic python-magic-bin

In [7]:
from langchain.document_loaders import UnstructuredURLLoader # type: ignore

In [8]:
loader = UnstructuredURLLoader(urls=[
    "https://www.zdnet.com/article/what-is-chatgpt-and-why-does-it-matter-heres-everything-you-need-to-know/",
    "https://www.facultyfocus.com/articles/teaching-with-technology-articles/artificial-intelligence-the-rise-of-chatgpt-and-its-implications/"
])

In [9]:
data = loader.load()
len(data)

2

In [10]:
data[0]

Document(page_content='Innovation\n\nWhy you can trust ZDNET\n\nZDNET independently tests and researches products to bring you our best recommendations and advice. When you buy through our links, we may earn a commission. Our process\n\n\'ZDNET Recommends\': What exactly does it mean?\n\nZDNET\'s recommendations are based on many hours of testing, research, and comparison shopping. We gather data from the best available sources, including vendor and retailer listings as well as other relevant and independent reviews sites. And we pore over customer reviews to find out what matters to real people who already own and use the products and services we’re assessing.\n\nWhen you click through from our site to a retailer and buy a product or service, we may earn affiliate commissions. This helps support our work, but does not affect what we cover or how, and it does not affect the price you pay. Neither ZDNET nor the author are compensated for these independent reviews.  Indeed, we follow str

In [11]:
text = """Interstellar is a 2014 epic science fiction drama film directed by Christopher Nolan, who co-wrote it with his brother Jonathan. It stars Matthew McConaughey, Anne Hathaway, Jessica Chastain, Bill Irwin, Ellen Burstyn, Michael Caine, and Matt Damon. Set in a dystopian future where Earth is suffering from catastrophic blight and famine, the film follows a group of astronauts who travel through a wormhole near Saturn in search of a new home for humankind.

The screenplay had its origins in a script Jonathan developed in 2007, and was originally set to be directed by Steven Spielberg. Theoretical physicist Kip Thorne was an executive producer and scientific consultant on the film, and wrote the tie-in book The Science of Interstellar. Cinematographer Hoyte van Hoytema shot it on 35 mm movie film in the Panavision anamorphic format and IMAX 70 mm. Filming began in late 2013 and took place in Alberta, Klaustur, and Los Angeles. Interstellar uses extensive practical and miniature effects, and the company DNEG created additional digital effects.

Interstellar premiered in Los Angeles on October 26, 2014. In the United States, it was first released on film stock, expanding to venues using digital projectors. The film received positive reviews from critics and grossed over $681 million worldwide ($733 million after subsequent re-releases), making it the tenth-highest-grossing film of 2014. It has been praised by astronomers for its scientific accuracy and portrayal of theoretical astrophysics.[4][5][6] Interstellar was nominated for five awards at the 87th Academy Awards, winning Best Visual Effects, and received numerous other accolades.

Plot
In 2067, humanity is facing extinction following a global famine caused by ecocide.[7] Joseph Cooper, a former NASA test pilot, along with his son and daughter, Tom and Murph, and father-in-law Donald, are farmers, like most of humanity. One evening, during a dust storm, Cooper and Murph discover a gravitational anomaly in Murph's bedroom that has left patterns of falling particles. The pattern leads them to a secret NASA facility, where Cooper is enlisted by the lead scientist, Brand, as the pilot of their latest mission, which will take them beyond the galaxy in search of new habitable planets. This can now be achieved via a mysterious wormhole − another anomaly − near Saturn, leading to a faraway planetary system orbiting Gargantua, a supermassive black hole.

Cooper struggles with leaving his children behind, but decides to do it in the hope of saving Tom and Murph's generation from extinction. He promises Murph he will return, but she is distraught. Cooper joins the Endurance team, consisting of Romilly, Doyle, and Brand's daughter Amelia − and two intelligent robots, TARS and CASE. After years of travel, the crew enters the wormhole and arrives at the first candidate planet in the new galaxy, only to find that it is an ocean world with massive tidal waves caused by Gargantua's intense gravitational pull. Doyle is swept away and killed by a wave. Cooper and Amelia narrowly survive, but are delayed returning to the Endurance. Due to time dilation, 23 years have passed onboard and on Earth during their absence from the craft. On Earth in 2092, an adult Murph helps Brand with his perennially unsolved gravity manipulation equation, which is supposed to help transport humanity en masse to potentially habitable worlds.

On his deathbed, Brand confesses that the equation was a charade, meant to keep humans from dissolving into anarchy out of panic for their eventual doom. Murph is frustrated and wonders if Cooper knowingly abandoned her. She decides to continue Brand's work, and returns to her childhood home to search for clues. On the second candidate planet, the Endurance crew is met by a harsh ice world. They awaken Mann, the surviving NASA explorer in cryostasis, who landed here a decade ago. Mann and Cooper go on a scouting trip, but once alone, Mann confesses that the planet is uninhabitable and that he falsified data to attract rescuers. He tries to kill Cooper but fails. Amelia is pulled into rescuing Cooper, leading Romilly to die at the base by an explosive trap left by Mann. Mann takes off in a lander, attempting to hijack the Endurance, but is killed in a failed docking maneuver. Cooper and Amelia chase down the damaged spacecraft, and narrowly dock with it though they have limited fuel remaining and are falling into the black hole."""

In [12]:
text[:200]

'Interstellar is a 2014 epic science fiction drama film directed by Christopher Nolan, who co-wrote it with his brother Jonathan. It stars Matthew McConaughey, Anne Hathaway, Jessica Chastain, Bill Irw'

In [13]:
from langchain.text_splitter import CharacterTextSplitter # problem is speartor is fixed

splitter = CharacterTextSplitter(
    separator="\n",
    chunk_size=200,
    chunk_overlap=0
)

chunks = splitter.split_text(text)
len(chunks)

Created a chunk of size 457, which is longer than the specified 200
Created a chunk of size 595, which is longer than the specified 200
Created a chunk of size 601, which is longer than the specified 200
Created a chunk of size 772, which is longer than the specified 200
Created a chunk of size 973, which is longer than the specified 200


7

In [14]:
chunks

['Interstellar is a 2014 epic science fiction drama film directed by Christopher Nolan, who co-wrote it with his brother Jonathan. It stars Matthew McConaughey, Anne Hathaway, Jessica Chastain, Bill Irwin, Ellen Burstyn, Michael Caine, and Matt Damon. Set in a dystopian future where Earth is suffering from catastrophic blight and famine, the film follows a group of astronauts who travel through a wormhole near Saturn in search of a new home for humankind.',
 'The screenplay had its origins in a script Jonathan developed in 2007, and was originally set to be directed by Steven Spielberg. Theoretical physicist Kip Thorne was an executive producer and scientific consultant on the film, and wrote the tie-in book The Science of Interstellar. Cinematographer Hoyte van Hoytema shot it on 35 mm movie film in the Panavision anamorphic format and IMAX 70 mm. Filming began in late 2013 and took place in Alberta, Klaustur, and Los Angeles. Interstellar uses extensive practical and miniature effect

In [15]:
from langchain.text_splitter import RecursiveCharacterTextSplitter

r_splitter = RecursiveCharacterTextSplitter(
    separators=["\n\n", "\n", " "],
    chunk_size = 200,
    chunk_overlap=0
) 

r_splitter.split_text(text)
len(chunks)

7

In [16]:
for chunk in chunks:
    print(len(chunks))

7
7
7
7
7
7
7


In [17]:
import pandas as pd

pd.set_option('display.max_colwidth', 100)


In [18]:
df = pd.read_csv("sample_text.csv")
df.shape

(8, 2)

In [19]:
df

text  \
0                                        Meditation and yoga can improve mental health   
1                     Fruits, whole grains and vegetables helps control blood pressure   
2                                    These are the latest fashion trends for this week   
3                                    Vibrant color jeans for male are becoming a trend   
4                                                   The concert starts at 7 PM tonight   
5                      Navaratri dandiya program at Expo center in Mumbai this october   
6                                    Exciting vacation destinations for your next trip   
7  Maldives and Srilanka are gaining popularity in terms of low budget vacation places   

  category  
0   Health  
1   Health  
2  Fashion  
3  Fashion  
4    Event  
5    Event  
6   Travel  
7   Travel

In [20]:
from sentence_transformers import SentenceTransformer

encoder = SentenceTransformer("all-mpnet-base-v2")
vectors = encoder.encode(df.text)
vectors.shape

d:\anaconda\envs\venv\Lib\site-packages\sentence_transformers\cross_encoder\CrossEncoder.py:11: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from tqdm.autonotebook import tqdm, trange
d:\anaconda\envs\venv\Lib\site-packages\huggingface_hub\file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


(8, 768)

In [21]:
vectors

array([[-0.00247396,  0.03626723, -0.05290459, ..., -0.09152357,
        -0.03970001, -0.04330489],
       [-0.03357268,  0.00980517, -0.03250129, ..., -0.05165466,
         0.02245888, -0.03156181],
       [-0.01865322, -0.04051315, -0.01235386, ...,  0.00610586,
        -0.07179644,  0.02773852],
       ...,
       [-0.00066459,  0.04252128, -0.05645508, ...,  0.01315471,
        -0.03183568, -0.04357662],
       [-0.03317154,  0.03252454, -0.02484838, ...,  0.0117442 ,
         0.05747125,  0.00571021],
       [-0.00166395,  0.00413827, -0.04597083, ...,  0.02008528,
         0.05656242, -0.00161596]], dtype=float32)

In [22]:
dim = vectors.shape[1]

In [24]:
import faiss

index = faiss.IndexFlatL2(dim)

In [25]:
index

<faiss.swigfaiss_avx2.IndexFlatL2; proxy of <Swig Object of type 'faiss::IndexFlatL2 *' at 0x0000027797287A20> >

In [26]:
index.add(vectors)

In [27]:
search_query="What is the importance of meditation"

vec = encoder.encode(search_query)
vec.shape

(768,)

In [28]:
import numpy as np
svec = np.array(vec).reshape(1,-1)
svec.shape

(1, 768)

In [29]:
svec

array([[ 1.25012547e-02,  8.10809955e-02, -2.20023654e-02,
        -2.57380940e-02, -6.01528073e-03,  1.99583769e-02,
        -1.14317797e-02,  1.26863308e-02, -4.50487956e-02,
        -4.17786390e-02,  1.04854139e-03, -2.09398344e-02,
        -1.75669901e-02, -6.65402785e-02,  2.12466213e-04,
        -5.78440875e-02,  3.50150769e-03,  4.62399982e-03,
        -5.65732345e-02,  5.29663265e-02, -2.49848701e-02,
        -3.81421261e-02, -3.52206378e-04,  2.99619455e-02,
        -2.47262102e-02,  1.29802071e-03,  3.31498049e-02,
         1.54495267e-02,  4.79244441e-02, -5.46999611e-02,
        -7.66371042e-02,  5.57240471e-03,  5.07056415e-02,
        -3.89018059e-02,  1.66872724e-06, -6.88856747e-03,
        -1.11288056e-02, -2.36922838e-02,  1.65387150e-03,
         1.22939041e-02,  5.36075793e-02,  7.09848246e-03,
         5.44139231e-03, -5.49256220e-04, -8.15594662e-03,
         4.86974418e-02,  8.76531657e-03,  6.63599349e-04,
         3.37240985e-03,  4.37944718e-02, -2.55895749e-0

In [30]:
distances, I = index.search(svec, k=2)

In [31]:
I

array([[0, 5]], dtype=int64)

In [32]:
search_query

'What is the importance of meditation'